// UIL Computer Science – Boolean Logic, Bitwise Operators, Digital Electronics
const BOOLEAN_LOGIC_PROBLEMS = [

  // ── BOOLEAN EXPRESSIONS ──
  { id: "bl1", topic: "Boolean Logic", question: "What is the value of <code>true && false || true</code>?", choices: ["true", "false", "Compilation error", "null", "undefined"], answer: 0, hint: "&& has higher precedence than ||", explanation: "(true && false) = false. false || true = true." },
  { id: "bl2", topic: "Boolean Logic", question: "What is the value of <code>!(true || false) && true</code>?", choices: ["true", "false", "Compilation error", "null", "1"], answer: 1, hint: "Evaluate the parentheses first, then negate, then AND", explanation: "(true || false) = true. !true = false. false && true = false." },
  { id: "bl3", topic: "Boolean Logic", question: "What is the value of <code>true ^ true</code> in Java?", choices: ["true", "false", "1", "0", "Compilation error"], answer: 1, hint: "^ is XOR: returns true only when operands differ", explanation: "XOR: true ^ true = false (both same → false)." },
  { id: "bl4", topic: "Boolean Logic", question: "What is the value of <code>false ^ true ^ false</code>?", choices: ["true", "false", "Compilation error", "0", "1"], answer: 0, hint: "Evaluate left to right: (false ^ true) = true, then true ^ false = true", explanation: "false ^ true = true. true ^ false = true." },

  // ── SHORT-CIRCUIT EVALUATION ──
  { id: "bl5", topic: "Boolean Logic", question: "What is the output?<pre><code>int x = 5;\nif (x > 10 && ++x > 5)\n  System.out.println(x);\nSystem.out.println(x);</code></pre>", choices: ["5", "6", "5 then 6", "6 then 6", "5 then 5"], answer: 0, hint: "Short-circuit: if the left side of && is false, the right side is never evaluated", explanation: "x > 10 is false. Due to short-circuit &&, ++x is never executed. x stays 5. Only the last println runs, printing 5." },
  { id: "bl6", topic: "Boolean Logic", question: "What is the output?<pre><code>int a = 3;\nif (a > 1 || ++a > 5)\n  System.out.println(a);</code></pre>", choices: ["3", "4", "5", "true", "No output"], answer: 0, hint: "Short-circuit ||: if the left side is true, the right side is skipped", explanation: "a > 1 is true. Due to short-circuit ||, ++a is never evaluated. a stays 3." },
  { id: "bl7", topic: "Boolean Logic", question: "What is the difference between <code>&amp;&amp;</code> and <code>&amp;</code> when used with boolean operands?", choices: ["No difference", "&amp;&amp; short-circuits, &amp; does not", "&amp; short-circuits, &amp;&amp; does not", "&amp; is bitwise only", "&amp;&amp; is bitwise only"], answer: 1, hint: "&amp;&amp; is the conditional AND (short-circuits); &amp; always evaluates both sides", explanation: "&& (conditional AND) short-circuits: if left is false, right is not evaluated. & (logical AND) always evaluates both operands." },

  // ── BITWISE OPERATORS ──
  { id: "bl8", topic: "Boolean Logic", question: "What is the value of <code>12 &amp; 10</code> in Java?", choices: ["2", "6", "8", "10", "14"], answer: 2, hint: "12 = 1100, 10 = 1010. AND bit by bit", explanation: "12 = 1100, 10 = 1010. 1100 & 1010 = 1000 = 8." },
  { id: "bl9", topic: "Boolean Logic", question: "What is the value of <code>12 | 10</code>?", choices: ["2", "6", "8", "10", "14"], answer: 4, hint: "12 = 1100, 10 = 1010. OR bit by bit", explanation: "12 = 1100, 10 = 1010. 1100 | 1010 = 1110 = 14." },
  { id: "bl10", topic: "Boolean Logic", question: "What is the value of <code>12 ^ 10</code>?", choices: ["2", "6", "8", "10", "14"], answer: 1, hint: "12 = 1100, 10 = 1010. XOR bit by bit", explanation: "12 = 1100, 10 = 1010. 1100 ^ 1010 = 0110 = 6." },
  { id: "bl11", topic: "Boolean Logic", question: "What is the value of <code>~5</code> in Java (as an int)?", choices: ["&minus;5", "&minus;6", "4", "5", "&minus;4"], answer: 1, hint: "Bitwise NOT flips all bits. ~n = &minus;(n+1)", explanation: "~5 = −(5+1) = −6. In binary, ~00000101 = 11111010 (two's complement for −6)." },
  { id: "bl12", topic: "Boolean Logic", question: "What is the value of <code>1 &lt;&lt; 4</code>?", choices: ["2", "4", "8", "16", "32"], answer: 3, hint: "Left shift by 4 is equivalent to multiplying by 2⁴", explanation: "1 << 4 = 1 × 2⁴ = 16." },
  { id: "bl13", topic: "Boolean Logic", question: "What is the value of <code>32 &gt;&gt; 3</code>?", choices: ["2", "4", "8", "16", "256"], answer: 1, hint: "Right shift by 3 is equivalent to dividing by 2³", explanation: "32 >> 3 = 32 / 2³ = 32 / 8 = 4." },

  // ── BOOLEAN SIMPLIFICATION ──
  { id: "bl14", topic: "Boolean Logic", question: "Which expression is equivalent to <code>!(A && B)</code>?", choices: ["!A && !B", "!A || !B", "A || B", "!A && B", "A && !B"], answer: 1, hint: "De Morgan's Law: !(A && B) = !A || !B", explanation: "By De Morgan's Law: !(A && B) = !A || !B." },
  { id: "bl15", topic: "Boolean Logic", question: "Which expression is equivalent to <code>!(A || B)</code>?", choices: ["!A && !B", "!A || !B", "A && B", "!A || B", "A && !B"], answer: 0, hint: "De Morgan's Law: !(A || B) = !A && !B", explanation: "By De Morgan's Law: !(A || B) = !A && !B." },
  { id: "bl16", topic: "Boolean Logic", question: "Simplify: <code>A && (A || B)</code>", choices: ["A", "B", "A && B", "A || B", "true"], answer: 0, hint: "This is the absorption law: A ∧ (A ∨ B) = A", explanation: "By the Absorption Law: A && (A || B) = A." },
  { id: "bl17", topic: "Boolean Logic", question: "Simplify: <code>(A && !B) || (A && B)</code>", choices: ["A", "B", "!B", "A && B", "A || B"], answer: 0, hint: "Factor out A: A && (!B || B) = A && true = A", explanation: "Factor out A: A && (!B || B) = A && true = A." },

  // ── DIGITAL LOGIC GATES ──
  { id: "bl18", topic: "Boolean Logic", question: "An AND gate with inputs 1 and 0 produces output:", choices: ["0", "1", "undefined", "error", "both"], answer: 0, hint: "AND requires both inputs to be 1", explanation: "AND gate: 1 AND 0 = 0. Both inputs must be 1 for output 1." },
  { id: "bl19", topic: "Boolean Logic", question: "A NAND gate with inputs 1 and 1 produces output:", choices: ["0", "1", "undefined", "error", "both"], answer: 0, hint: "NAND = NOT AND. AND(1,1) = 1, then NOT(1) = 0", explanation: "NAND(1,1) = NOT(1 AND 1) = NOT(1) = 0." },
  { id: "bl20", topic: "Boolean Logic", question: "An XOR gate with inputs 0 and 0 produces output:", choices: ["0", "1", "undefined", "error", "both"], answer: 0, hint: "XOR outputs 1 only when inputs are different", explanation: "XOR(0,0) = 0. Inputs are the same, so output is 0." },
  { id: "bl21", topic: "Boolean Logic", question: "A NOR gate with inputs 0 and 0 produces output:", choices: ["0", "1", "undefined", "error", "both"], answer: 1, hint: "NOR = NOT OR. OR(0,0) = 0, NOT(0) = 1", explanation: "NOR(0,0) = NOT(0 OR 0) = NOT(0) = 1." },
  { id: "bl22", topic: "Boolean Logic", question: "Which gate produces 1 only when both inputs are 0?", choices: ["AND", "OR", "NAND", "NOR", "XOR"], answer: 3, hint: "NOR outputs 1 only when all inputs are 0", explanation: "NOR: NOT(A OR B). Only when A=0 and B=0 does OR give 0 and NOT gives 1." },

  // ── POLISH NOTATION ──
  { id: "bl23", topic: "Boolean Logic", question: "Convert the infix expression <code>3 + 4 * 5</code> to postfix (RPN).", choices: ["3 4 + 5 *", "3 4 5 * +", "* + 3 4 5", "+ 3 * 4 5", "3 4 5 + *"], answer: 1, hint: "In postfix, operators come after their operands. * has higher precedence", explanation: "4 * 5 first → 4 5 *. Then 3 + result → 3 4 5 * +." },
  { id: "bl24", topic: "Boolean Logic", question: "Evaluate the postfix expression <code>5 3 + 4 *</code>.", choices: ["17", "23", "32", "35", "60"], answer: 2, hint: "Push numbers, when you see an operator pop two operands and apply", explanation: "Push 5, 3. +: pop 5,3 → 8. Push 4. *: pop 8,4 → 32." },
  { id: "bl25", topic: "Boolean Logic", question: "Convert the infix expression <code>(A + B) * C</code> to prefix (Polish notation).", choices: ["* + A B C", "+ A * B C", "A B + C *", "* A + B C", "A + B * C"], answer: 0, hint: "In prefix notation, the operator comes before its operands", explanation: "A + B → + A B. Then (+ A B) * C → * + A B C." },
];
