// UIL Computer Science – Code Tracing (Complex multi-step traces)
// Matches real UIL Q16–Q40 difficulty. Uses out.print/out.println (static import).
const CODE_TRACING_PROBLEMS = [

  // ══════════════════════════════════════════
  //  MEDIUM TRACES – Strings, Math, mixed ops
  // ══════════════════════════════════════════

  { id: "ct1", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>String s = \"ABCDEF\";\nout.println(s.substring(1, 4) +\n    s.charAt(5));</code></pre>", choices: ["BCDF", "BCDE", "ABCF", "BCDEF", "There is no output due to a compile error."], answer: 0, hint: "substring(1,4) = chars at indices 1,2,3. charAt(5) = index 5", explanation: "substring(1,4) = \"BCD\". charAt(5) = 'F'. \"BCD\" + 'F' = \"BCDF\"." },

  { id: "ct2", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>double x = 0, y = 0;\nx /= y--;\nout.print((y == x) + \" \");\nout.print(y);</code></pre>", choices: ["false -1.0", "true -1.0", "false 0.0", "There is no output due to a runtime error.", "There is no output due to a compile error."], answer: 0, hint: "y-- uses 0.0 then decrements. 0.0/0.0 = NaN. NaN == anything is false", explanation: "y-- evaluates to 0.0 (y becomes -1.0). x = 0.0/0.0 = NaN. NaN == -1.0 is false. Output: \"false -1.0\"." },

  { id: "ct3", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>int alpha = 10;\nint beta = ++alpha;\nint gamma = alpha++;\nout.println(alpha + \" \" + beta\n    + \" \" + gamma);</code></pre>", choices: ["10 10 11", "11 11 11", "12 11 11", "12 11 12", "There is no output due to a compile error."], answer: 2, hint: "++alpha increments then uses (11). alpha++ uses then increments (11→12)", explanation: "++alpha: alpha→11, beta=11. alpha++: gamma=11, alpha→12. Output: \"12 11 11\"." },

  { id: "ct4", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>double gpa = 3.961;\nString latinHonors = \"none\";\nswitch(gpa) {\n    case 3.731: latinHonors = \"Cum Laude\";\n        break;\n    case 3.886: latinHonors = \"Magna\";\n        break;\n    case 3.976: latinHonors = \"Summa\";\n        break;\n}\nout.println(latinHonors);</code></pre>", choices: ["none", "Cum Laude", "Magna", "Summa", "There is no output due to a compile error."], answer: 4, hint: "Can you use a double as a switch expression in Java?", explanation: "Java switch does not support double. Only int, byte, short, char, String, and enums. Compile error." },

  { id: "ct5", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>int i = 4;\nswitch(5) {\n    case 4: i += 10;\n    case 2: i++;\n        break;\n    default: i += 100;\n}\nout.print(i);</code></pre>", choices: ["4", "15", "104", "105", "There is no output due to a compile error."], answer: 2, hint: "switch(5) doesn't match case 4 or case 2. Falls into default", explanation: "5 doesn't match 4 or 2. Hits default: i += 100 → i = 104. Output: 104." },

  // ══════════════════════════════════════════
  //  LOOP TRACES – nested, complex state
  // ══════════════════════════════════════════

  { id: "ct6", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>int sum = 0;\nfor(int y = 5; y < 16; y++)\n    for(int x = y; x >= 10; x--)\n        sum += x;\nout.println(sum);</code></pre>", choices: ["75", "170", "200", "245", "There is no output due to a compile error."], answer: 3, hint: "Inner loop only runs when y >= 10. For y=10: x=10. For y=11: x=11,10. Etc.", explanation: "y=5-9: inner loop doesn't run. y=10: sum+=10 (10). y=11: sum+=11+10 (31). y=12: sum+=12+11+10 (64). y=13: sum+=13+12+11+10 (110). y=14: sum+=14+13+12+11+10 (170). y=15: sum+=15+14+13+12+11+10 (245). Total = 245." },

  { id: "ct7", topic: "Code Tracing", question: "How many *'s are output by the code to the right?<pre><code>for(int y = 9; y < 123; y = y * 2 - 7)\n    out.print(\"*\");\nout.println();</code></pre>", choices: ["5", "6", "7", "8", "There is no output due to an infinite loop."], answer: 1, hint: "Trace y: 9, 11, 15, 23, 39, 71, 135. How many are < 123?", explanation: "y: 9→11→15→23→39→71→135. Values < 123: 9,11,15,23,39,71. That's 6 iterations → 6 stars." },

  { id: "ct8", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>int i = 0, ii = 10, n = 0;\nfor(;i <= ii;) {\n    ii++;\n    i += ii / 10;\n    n++;\n}\nout.println(n + \" \" + ii);</code></pre>", choices: ["22 32", "20 30", "21 31", "19 29", "There is no output due to an infinite loop."], answer: 1, hint: "Each iteration: ii increments by 1, i increments by ii/10 (integer division). Track when i > ii", explanation: "Each iter: ii++, then i += ii/10. ii grows by 1, i grows by floor(ii/10). i stays behind until it catches up. After 20 iterations, i > ii. n=20, ii=30. Output: 20 30." },

  { id: "ct9", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>for(int off = 1; off < 25; off *= 2) {\n    out.print(('A' + off) + \" \");\n}\nout.println();\nfor(int off = 1; off < 25; off *= 2) {\n    out.print((off + 'A') + \" \");\n}</code></pre>", choices: ["66 67 69 73 81\\n66 67 69 73 81", "B C E I Q\\nB C E I Q", "B C E I Q\\n66 67 69 73 81", "66 67 69 73 81\\nB C E I Q", "There is no output due to a compile error."], answer: 0, hint: "Both loops compute 'A' + off (or off + 'A') — char + int = int in both cases. + is commutative for arithmetic", explanation: "'A'=65. off=1,2,4,8,16. Both loops compute int+char = int. 65+1=66, 65+2=67, 65+4=69, 65+8=73, 65+16=81. Since char+int=int in both orderings, both lines print: 66 67 69 73 81." },

  // ══════════════════════════════════════════
  //  ARRAY TRACES – 2D arrays, complex indices
  // ══════════════════════════════════════════

  { id: "ct10", topic: "Code Tracing", question: "What is output by the line marked <code>//q10</code> in the code to the right?<pre><code>int[][] mat = new int[3][5];\nfor(int r = 0; r < 3; r++)\n    for(int c = 4; c >= 0; c--)\n        mat[r][c] =\n            (r + 1) * 5 + (c - 1) * c - 2;\nout.println(\n    Arrays.toString(mat[2])); //q10</code></pre>", choices: ["[13, 13, 15, 19, 25]", "[-2, -2, 0, 4, 10]", "[8, 8, 10, 14, 20]", "[3, 3, 5, 9, 15]", "There is no output due to a runtime error."], answer: 0, hint: "For row r=2: (2+1)*5 + (c-1)*c - 2. Compute for c=0,1,2,3,4", explanation: "r=2: formula = (2+1)*5 + (c-1)*c - 2 = 15 + (c-1)*c - 2. c=0: 15+0-2=13. c=1: 15+0-2=13. c=2: 15+2-2=15. c=3: 15+6-2=19. c=4: 15+12-2=25. mat[2] = [13, 13, 15, 19, 25]." },

  { id: "ct11", topic: "Code Tracing", question: "What is output by the line marked <code>//q11</code> in the code to the right?<pre><code>int[][] mat = new int[3][5];\nfor(int r = 0; r < 3; r++)\n    for(int c = 4; c >= 0; c--)\n        mat[r][c] =\n            (r + 1) * 5 + (c - 1) * c - 2;\nfor(int i = 0; i < 4; i++) {\n    if(i != 3) {\n        mat[i][i] = mat[i][i + 1];\n        mat[i][i]--;\n    } if(i != 0) {\n        mat[i - 1][i + 1] =\n            mat[i - 1][i - 1];\n        mat[i - 1][i]++;\n    }\n}\nout.println(\n    Arrays.toString(mat[1])); //q11</code></pre>", choices: ["[8, 8, 10, 14, 20]", "[8, 9, 11, 9, 20]", "[8, 7, 11, 14, 20]", "[8, 9, 10, 14, 20]", "There is no output due to a runtime error."], answer: 1, hint: "Initial mat[1]=[8,8,10,14,20]. The second loop modifies entries. No runtime error — all indices stay in bounds", explanation: "Initial mat: row0=[3,3,5,9,15], row1=[8,8,10,14,20], row2=[13,13,15,19,25]. Loop modifies entries: i=0: mat[0][0]=mat[0][1]-1=2. i=1: mat[1][1]=mat[1][2]-1=9, then mat[0][2]=mat[0][0]=2, mat[0][1]++→4. i=2: mat[2][2]=mat[2][3]-1=18, then mat[1][3]=mat[1][1]=9, mat[1][2]++→11. i=3: skip i!=3, then mat[2][4]=mat[2][2]=18, mat[2][3]++→20. Final mat[1]=[8, 9, 11, 9, 20]." },

  // ══════════════════════════════════════════
  //  ARRAYLIST / COLLECTIONS TRACES
  // ══════════════════════════════════════════

  { id: "ct12", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>ArrayList&lt;String&gt; a;\na = new ArrayList&lt;&gt;();\na.add(\"ABC\"); a.add(\"DEF\");\na.add(\"GHIJK\"); a.add(\"LMNOP\");\na.add(\"QRS\"); a.add(\"TUV\");\na.add(\"WXYZ\");\na.removeIf(s -> s.length() < 4);\nout.println(a);</code></pre>", choices: ["[GHIJK, LMNOP, WXYZ]", "[ABC, DEF, QRS, TUV]", "[GHIJK, LMNOP]", "[GHIJK, LMNOP, WXYZ, ABC]", "There is no output due to a compile error."], answer: 0, hint: "removeIf removes elements where the lambda returns true. Which strings have length < 4?", explanation: "Strings: ABC(3), DEF(3), GHIJK(5), LMNOP(5), QRS(3), TUV(3), WXYZ(4). Remove where length < 4: remove ABC, DEF, QRS, TUV. Remaining: [GHIJK, LMNOP, WXYZ]." },

  { id: "ct13", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>ArrayList&lt;Integer&gt; a;\na = new ArrayList&lt;&gt;();\nfor(int y = 1; y < 30; y += 4)\n    a.add(y);\nCollections.rotate(a, -3);\nout.println(a);</code></pre>", choices: ["[13, 17, 21, 25, 29, 1, 5, 9]", "[9, 1, 5, 13, 17, 21, 25, 29]", "[1, 5, 9, 13, 17, 21, 25, 29]", "[25, 29, 1, 5, 9, 13, 17, 21]", "There is no output due to a compile error."], answer: 0, hint: "Build list first: y=1,5,9,13,17,21,25,29. rotate(-3) shifts left by 3 positions", explanation: "List: [1,5,9,13,17,21,25,29]. Collections.rotate(a, -3): left-rotate by 3. First 3 elements go to end: [13,17,21,25,29,1,5,9]." },

  { id: "ct14", topic: "Code Tracing", question: "What is output by the line marked <code>//q14</code> in the code to the right?<pre><code>ArrayList&lt;String&gt; a;\na = new ArrayList&lt;&gt;();\na.add(\"ABC\");a.add(\"DEF\");\na.add(\"GHIJK\");a.add(\"LMNOP\");\na.add(\"QRS\");a.add(\"TUV\");\na.add(\"WXYZ\");\na.removeIf(s -> s.length() < 4);\nout.println(a); //q14\na.forEach(s -> {\n    for(int i = 0;\n        i < s.length(); i += 2)\n        out.print(s.charAt(i));\n}); //q15</code></pre>", choices: ["[GHIJK, LMNOP, WXYZ]", "[ABC, DEF, QRS, TUV]", "[GHIJK, LMNOP]", "[GHIJK, LMNOP, WXYZ, ABC]", "There is no output due to a compile error."], answer: 0, hint: "Same as before: removeIf removes strings with length < 4", explanation: "After removeIf: [GHIJK, LMNOP, WXYZ]. //q14 prints that list." },

  { id: "ct15", topic: "Code Tracing", question: "What is output by the line marked <code>//q15</code> in the code from the previous question?", choices: ["GIKLNPWY", "GHIJKLMNOPWXYZ", "GILNOWYXZ", "GIKLNOWY", "There is no output due to a compile error."], answer: 0, hint: "forEach iterates over [GHIJK, LMNOP, WXYZ]. Inner loop prints every other character (i+=2)", explanation: "GHIJK: indices 0,2,4 → G,I,K. LMNOP: indices 0,2,4 → L,N,P. WXYZ: indices 0,2 → W,Y. Total: GIKLNPWY." },

  // ══════════════════════════════════════════
  //  RECURSION TRACES
  // ══════════════════════════════════════════

  { id: "ct16", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>public static int recur(int i) {\n    if(i < 0)\n        return 1;\n    if(i % 5 < 2)\n        return recur(i - 2) +\n               recur(i - 3);\n    else\n        return recur(i - 2);\n}\n//client code:\nout.println(recur(10));</code></pre>", choices: ["5", "8", "12", "13", "There is no output due to a runtime error."], answer: 1, hint: "Trace: recur(10)→10%5=0<2→recur(8)+recur(7). Continue expanding each branch", explanation: "r(10)=r(8)+r(7). r(8)=r(6) [8%5=3≥2]. r(7)=r(5) [7%5=2≥2]. r(6)=r(4)+r(3) [6%5=1<2]. r(5)=r(3)+r(2) [5%5=0<2]. r(4)=r(2) [4%5=4≥2]. r(3)=r(1) [3%5=3≥2]. r(2)=r(0) [2%5=2≥2]. r(1)=r(-1)+r(-2) [1%5=1<2]=1+1=2. r(0)=r(-2)+r(-3) [0%5=0<2]=1+1=2. r(2)=r(0)=2. r(3)=r(1)=2. r(4)=r(2)=2. r(5)=2+2=4. r(6)=2+2=4. r(7)=r(5)=4. r(8)=r(6)=4. r(10)=4+4=8." },

  { id: "ct17", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>public static void mirror(int n) {\n    if(n > 0) {\n        out.print(n + \" \");\n        mirror(n - 1);\n        out.print(n + \" \");\n    }\n}\n//client code:\nmirror(4);</code></pre>", choices: ["4 3 2 1 1 2 3 4", "4 3 2 1", "1 2 3 4 4 3 2 1", "4 3 2 1 2 3 4", "There is no output due to a runtime error."], answer: 0, hint: "Each call prints n, recurses, then prints n again (mirror pattern)", explanation: "mirror(4): print 4, mirror(3): print 3, mirror(2): print 2, mirror(1): print 1, mirror(0): base case. Then unwind: print 1, print 2, print 3, print 4. Output: 4 3 2 1 1 2 3 4." },

  { id: "ct18", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>public static int mystery(int n) {\n    if(n < 10) return n;\n    return n % 10 +\n        mystery(n / 10);\n}\n//client code:\nout.println(mystery(4821));</code></pre>", choices: ["4", "8", "12", "15", "There is no output due to a runtime error."], answer: 3, hint: "This recursively extracts and sums each digit of n", explanation: "mystery(4821)=1+mystery(482)=1+2+mystery(48)=1+2+8+mystery(4)=1+2+8+4=15." },

  // ══════════════════════════════════════════
  //  OOP / INHERITANCE TRACES
  // ══════════════════════════════════════════

  { id: "ct19", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>class A {\n    int i; String s;\n    public A(int i, String s) {\n        this.i = i; this.s = s;\n    }\n    public int add() {\n        return ++i;\n    }\n    public String toString() {\n        return s + \" \" + i;\n    }\n}\nclass B extends A {\n    public B(String s) {\n        super(3, s);\n    }\n    public int add() {\n        i += 2; super.add();\n        return i;\n    }\n}\n//client code:\nA a = new A(3, \"a\");\nB b = new B(\"b\");\nString o = \"\" + a.add();\no += \" \" + b.add();\no += \" \" + c.add();\nout.println(o); //q19</code></pre>", choices: ["4 6 7", "4 7 8", "4 6 8", "4 6 10", "There is no output due to a compile error."], answer: 4, hint: "Look carefully — is variable 'c' ever declared?", explanation: "Variable 'c' is never declared. c.add() causes a compile error." },

  { id: "ct20", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>class A {\n    int x = 5;\n    public int getX() { return x; }\n}\nclass B extends A {\n    int x = 10;\n    public int getX() { return x; }\n}\n//client code:\nA obj = new B();\nout.println(obj.x + \" \" +\n    obj.getX());</code></pre>", choices: ["5 5", "5 10", "10 10", "10 5", "There is no output due to a compile error."], answer: 1, hint: "Fields are bound by reference type (A), methods are bound by object type (B) — polymorphism", explanation: "obj.x: field access uses compile-time type (A), so A.x = 5. obj.getX(): method call uses runtime type (B), so B.getX() returns B.x = 10. Output: \"5 10\"." },

  // ══════════════════════════════════════════
  //  HASHMAP / REGEX / SCANNER TRACES
  // ══════════════════════════════════════════

  { id: "ct21", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>String k =\n    \"123\\nSB Th3\\tKoie 8293m\";\nScanner sc = new Scanner(k);\nsc.nextLine();\nsc.next();\nsc.next();\nout.println(sc.next());</code></pre>", choices: ["Koie", "SB Th3", "Koie 8293m", "Th3", "There is no output due to a runtime error."], answer: 0, hint: "nextLine() consumes \"123\". Then next() reads tokens split by whitespace from the second line: \"SB\", \"Th3\", \"Koie\", \"8293m\"", explanation: "After nextLine(): consumed \"123\". Remaining: \"SB Th3\\tKoie 8293m\". next()→\"SB\". next()→\"Th3\". next()→\"Koie\". Output: \"Koie\"." },

  { id: "ct22", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>String m1 = \"(\\\\w+ ){2,7}\";\nString m2 = \"([A-Z]?[a-z]* ?)+\";\nString s = \"One of a Kind\";\nout.print(s.matches(m1));\nout.print(\" \");\nout.print(s.matches(m2));</code></pre>", choices: ["true true", "true false", "false true", "false false", "There is no output due to a compile error."], answer: 2, hint: "m1 requires each group to end with a space — \"Kind\" doesn't. m2 allows optional uppercase + lowercase + optional space", explanation: "m1 = (\\w+ ){2,7}: each group needs word+space. \"Kind\" has no trailing space → false. m2 = ([A-Z]?[a-z]* ?)+: matches optional uppercase, lowercase*, optional space, repeated. \"One of a Kind\" matches. Output: \"false true\"." },

  { id: "ct23", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>HashMap&lt;String, Integer&gt; map;\nmap = new HashMap&lt;&gt;();\nString s = \"banana\";\nfor(char c : s.toCharArray()) {\n    String key = \"\" + c;\n    map.put(key,\n        map.getOrDefault(key, 0) + 1);\n}\nout.println(map.get(\"a\") + \" \" +\n    map.get(\"n\"));</code></pre>", choices: ["3 2", "2 3", "3 3", "2 2", "There is no output due to a runtime error."], answer: 0, hint: "Count character frequencies in \"banana\": b=1, a=3, n=2", explanation: "\"banana\": b(1), a(3), n(2), a(already counted). map.get(\"a\")=3, map.get(\"n\")=2. Output: \"3 2\"." },

  // ══════════════════════════════════════════
  //  COMPLEX MULTI-STEP TRACES
  // ══════════════════════════════════════════

  { id: "ct24", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>int n = 156;\nString hex = \"\";\nwhile(n > 0) {\n    int r = n % 16;\n    hex = (r < 10 ?\n        (char)('0' + r) :\n        (char)('A' + r - 10)) + hex;\n    n /= 16;\n}\nout.println(hex);</code></pre>", choices: ["9C", "9D", "A0", "98", "9B"], answer: 0, hint: "This converts decimal to hex. 156 / 16 = 9 remainder 12. 12 → 'C'", explanation: "156 % 16 = 12 → 'C'. 156/16 = 9. 9 % 16 = 9 → '9'. hex = \"9C\"." },

  { id: "ct25", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>Stack&lt;Integer&gt; stk = new Stack&lt;&gt;();\nfor(int i = 1; i <= 6; i++)\n    stk.push(i * 10);\nint sum = 0;\nwhile(stk.size() > 2) {\n    sum += stk.pop();\n}\nout.println(sum + \" \" + stk.peek());</code></pre>", choices: ["180 20", "150 30", "180 30", "210 10", "There is no output due to a runtime error."], answer: 0, hint: "Stack: [10,20,30,40,50,60] (bottom to top). Pop until size=2. Pop 60+50+40+30", explanation: "Push: 10,20,30,40,50,60. Pop while size>2: pop 60(size=5), pop 50(size=4), pop 40(size=3), pop 30(size=2, stop). sum=60+50+40+30=180. stk=[10,20]. peek()=20. Output: 180 20." },

  { id: "ct26", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>String[] words = \n    {\"the\", \"quick\", \"brown\",\n     \"fox\", \"jumps\"};\nString result = \"\";\nfor(String w : words)\n    result += w.charAt(0);\nout.println(\n    result.toUpperCase());</code></pre>", choices: ["TQBFJ", "tqbfj", "THE QUICK BROWN FOX JUMPS", "thequickbrownfoxjumps", "There is no output due to a compile error."], answer: 0, hint: "Takes first character of each word, concatenates, then converts to uppercase", explanation: "First chars: t,q,b,f,j → \"tqbfj\". toUpperCase() → \"TQBFJ\"." },

  { id: "ct27", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>int[] arr = {3, 1, 4, 1, 5, 9};\nfor(int i = 0;\n    i < arr.length - 1; i++) {\n    if(arr[i] > arr[i + 1]) {\n        int t = arr[i];\n        arr[i] = arr[i + 1];\n        arr[i + 1] = t;\n    }\n}\nout.println(arr[arr.length - 1]);</code></pre>", choices: ["1", "4", "5", "9", "There is no output due to a runtime error."], answer: 3, hint: "This is one pass of bubble sort — the largest element bubbles to the end", explanation: "One bubble pass: [3,1,4,1,5,9]→[1,3,4,1,5,9]→[1,3,4,1,5,9]→[1,3,1,4,5,9]→[1,3,1,4,5,9]→[1,3,1,4,5,9]. 9 was already at end. arr[5]=9." },

  { id: "ct28", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>int[][] grid = {\n    {1, 2, 3},\n    {4, 5, 6},\n    {7, 8, 9}\n};\nint sum = 0;\nfor(int r = 0; r < 3; r++)\n    sum += grid[r][r];\nout.println(sum);</code></pre>", choices: ["6", "12", "15", "18", "45"], answer: 2, hint: "grid[r][r] traces the main diagonal: grid[0][0], grid[1][1], grid[2][2]", explanation: "Diagonal: grid[0][0]=1, grid[1][1]=5, grid[2][2]=9. Sum = 15." },

  { id: "ct29", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>TreeMap&lt;String, Integer&gt; tm;\ntm = new TreeMap&lt;&gt;();\ntm.put(\"banana\", 3);\ntm.put(\"apple\", 1);\ntm.put(\"cherry\", 2);\ntm.put(\"apple\", 5);\nout.println(tm);</code></pre>", choices: ["{apple=1, banana=3, cherry=2}", "{apple=5, banana=3, cherry=2}", "{banana=3, apple=1, cherry=2, apple=5}", "{banana=3, apple=5, cherry=2}", "There is no output due to a compile error."], answer: 1, hint: "TreeMap sorts by key. Putting \"apple\" again overwrites the old value", explanation: "TreeMap sorts keys alphabetically. Second put(\"apple\",5) overwrites value 1→5. Output: {apple=5, banana=3, cherry=2}." },

  { id: "ct30", topic: "Code Tracing", question: "What is output by the code to the right?<pre><code>ArrayList&lt;Integer&gt; list;\nlist = new ArrayList&lt;&gt;();\nfor(int i = 1; i <= 5; i++)\n    list.add(i * 10);\nlist.remove(2);\nlist.add(1, 99);\nout.println(list);</code></pre>", choices: ["[10, 99, 20, 40, 50]", "[10, 99, 30, 40, 50]", "[10, 99, 40, 50]", "[99, 10, 20, 40, 50]", "There is no output due to a compile error."], answer: 0, hint: "After loop: [10,20,30,40,50]. remove(2) removes index 2 (value 30). add(1,99) inserts 99 at index 1", explanation: "Initial: [10,20,30,40,50]. remove(2) → [10,20,40,50]. add(1,99) → [10,99,20,40,50]." },
];
