// UIL Computer Science – Control Flow (Conditionals, Loops, Accumulation)
const CONTROL_FLOW_PROBLEMS = [

  // ── IF / ELSE ──
  { id: "cf1", topic: "Control Flow", question: "What is the output?<pre><code>int x = 15;\nif (x > 20)\n  System.out.print(\"A\");\nelse if (x > 10)\n  System.out.print(\"B\");\nelse\n  System.out.print(\"C\");\nSystem.out.print(\"D\");</code></pre>", choices: ["\"AD\"", "\"BD\"", "\"CD\"", "\"ABCD\"", "\"ABD\""], answer: 1, hint: "x=15 fails x>20, passes x>10, so the else-if branch executes", explanation: "x=15: x>20 false, x>10 true → prints \"B\". Then \"D\" always prints. Output: \"BD\"." },
  { id: "cf2", topic: "Control Flow", question: "What is the output?<pre><code>int a = 5, b = 10;\nif (a > 3)\n  if (b < 8)\n    System.out.print(\"X\");\n  else\n    System.out.print(\"Y\");\nelse\n  System.out.print(\"Z\");</code></pre>", choices: ["\"X\"", "\"Y\"", "\"Z\"", "\"XY\"", "\"YZ\""], answer: 1, hint: "The else matches the nearest if (dangling else). a>3 is true, b<8 is false", explanation: "a>3 is true, so we enter. b<8 is false, so else prints \"Y\"." },

  // ── SWITCH ──
  { id: "cf3", topic: "Control Flow", question: "What is the output?<pre><code>int n = 2;\nswitch(n) {\n  case 1: System.out.print(\"A\");\n  case 2: System.out.print(\"B\");\n  case 3: System.out.print(\"C\");\n  default: System.out.print(\"D\");\n}</code></pre>", choices: ["\"B\"", "\"BC\"", "\"BCD\"", "\"ABCD\"", "\"BD\""], answer: 2, hint: "No break statements, so execution falls through from case 2", explanation: "n=2 matches case 2. No breaks, so fall-through: prints \"B\", \"C\", \"D\". Output: \"BCD\"." },
  { id: "cf4", topic: "Control Flow", question: "What is the output?<pre><code>int val = 3;\nswitch(val) {\n  case 1: System.out.print(\"A\"); break;\n  case 2: System.out.print(\"B\"); break;\n  case 3: System.out.print(\"C\"); break;\n  default: System.out.print(\"D\");\n}</code></pre>", choices: ["\"A\"", "\"B\"", "\"C\"", "\"D\"", "\"CD\""], answer: 2, hint: "val=3 matches case 3 and the break prevents fall-through", explanation: "val=3 matches case 3, prints \"C\", then break exits the switch." },

  // ── TERNARY ──
  { id: "cf5", topic: "Control Flow", question: "What is the value of <code>int result = (7 > 5) ? 10 : 20;</code>?", choices: ["5", "7", "10", "20", "true"], answer: 2, hint: "condition ? valueIfTrue : valueIfFalse", explanation: "7 > 5 is true, so result = 10." },
  { id: "cf6", topic: "Control Flow", question: "What is the output?<pre><code>int x = 4;\nString s = (x % 2 == 0) ? \"even\" : \"odd\";\nSystem.out.println(s);</code></pre>", choices: ["\"even\"", "\"odd\"", "\"4\"", "\"true\"", "Compilation error"], answer: 0, hint: "4 % 2 == 0 is true", explanation: "4 % 2 = 0, so condition is true. s = \"even\"." },

  // ── FOR LOOPS ──
  { id: "cf7", topic: "Control Flow", question: "What is the output?<pre><code>for (int i = 0; i < 5; i++)\n  System.out.print(i + \" \");</code></pre>", choices: ["\"0 1 2 3 4 \"", "\"1 2 3 4 5 \"", "\"0 1 2 3 4 5 \"", "\"1 2 3 4 \"", "\"0 1 2 3 \""], answer: 0, hint: "i starts at 0 and goes up to (not including) 5", explanation: "i goes: 0, 1, 2, 3, 4. Output: \"0 1 2 3 4 \"." },
  { id: "cf8", topic: "Control Flow", question: "What is the output?<pre><code>for (int i = 10; i >= 1; i -= 3)\n  System.out.print(i + \" \");</code></pre>", choices: ["\"10 7 4 1 \"", "\"10 7 4 \"", "\"10 8 6 4 2 \"", "\"10 7 3 \"", "\"10 7 4 1 0 \""], answer: 0, hint: "Start at 10, subtract 3 each time while i >= 1", explanation: "i: 10, 7, 4, 1 (all ≥ 1). Next would be −2 which fails. Output: \"10 7 4 1 \"." },
  { id: "cf9", topic: "Control Flow", question: "How many times does this loop execute?<pre><code>for (int i = 1; i <= 100; i *= 2)\n  System.out.println(i);</code></pre>", choices: ["5", "6", "7", "8", "100"], answer: 2, hint: "i doubles each time: 1, 2, 4, 8, 16, 32, 64, then 128 > 100", explanation: "i: 1, 2, 4, 8, 16, 32, 64 (7 iterations). Next is 128 > 100." },

  // ── WHILE LOOPS ──
  { id: "cf10", topic: "Control Flow", question: "What is the output?<pre><code>int n = 5;\nwhile (n > 0) {\n  System.out.print(n + \" \");\n  n -= 2;\n}</code></pre>", choices: ["\"5 3 1 \"", "\"5 4 3 2 1 \"", "\"5 3 \"", "\"5 3 1 &minus;1 \"", "\"4 2 0 \""], answer: 0, hint: "n starts at 5 and decreases by 2: 5, 3, 1 (all > 0)", explanation: "n: 5 (print), 3 (print), 1 (print), −1 (fails condition). Output: \"5 3 1 \"." },
  { id: "cf11", topic: "Control Flow", question: "What is the output?<pre><code>int x = 1;\nwhile (x < 50) {\n  x *= 3;\n}\nSystem.out.println(x);</code></pre>", choices: ["27", "48", "54", "81", "243"], answer: 3, hint: "x triples each time: 1, 3, 9, 27, 81. 81 is the first value ≥ 50", explanation: "x: 1→3→9→27→81. At 81, condition x<50 is false. Prints 81." },

  // ── DO-WHILE ──
  { id: "cf12", topic: "Control Flow", question: "What is the output?<pre><code>int i = 10;\ndo {\n  System.out.print(i + \" \");\n  i++;\n} while (i < 10);</code></pre>", choices: ["No output", "\"10 \"", "\"10 11 \"", "Infinite loop", "Compilation error"], answer: 1, hint: "do-while always executes the body at least once", explanation: "Body executes once: prints \"10 \". Then i=11, condition i<10 is false. Stops." },

  // ── BREAK & CONTINUE ──
  { id: "cf13", topic: "Control Flow", question: "What is the output?<pre><code>for (int i = 0; i < 10; i++) {\n  if (i == 5) break;\n  System.out.print(i + \" \");\n}</code></pre>", choices: ["\"0 1 2 3 4 \"", "\"0 1 2 3 4 5 \"", "\"0 1 2 3 \"", "\"5 \"", "\"0 1 2 3 4 6 7 8 9 \""], answer: 0, hint: "break exits the loop entirely when i reaches 5", explanation: "When i=5, break exits the loop. Prints: \"0 1 2 3 4 \"." },
  { id: "cf14", topic: "Control Flow", question: "What is the output?<pre><code>for (int i = 0; i < 6; i++) {\n  if (i % 2 == 0) continue;\n  System.out.print(i + \" \");\n}</code></pre>", choices: ["\"0 2 4 \"", "\"1 3 5 \"", "\"1 2 3 4 5 \"", "\"0 1 2 3 4 5 \"", "\"2 4 6 \""], answer: 1, hint: "continue skips to the next iteration when i is even", explanation: "continue skips even i values. Prints odd values: \"1 3 5 \"." },

  // ── NESTED LOOPS ──
  { id: "cf15", topic: "Control Flow", question: "What is the output?<pre><code>for (int i = 1; i <= 3; i++)\n  for (int j = 1; j <= 2; j++)\n    System.out.print(i * j + \" \");</code></pre>", choices: ["\"1 2 2 4 3 6 \"", "\"1 2 3 4 5 6 \"", "\"2 4 6 \"", "\"1 4 9 \"", "\"1 2 3 2 4 6 \""], answer: 0, hint: "i goes 1-3, j goes 1-2 for each i. Print i×j each time", explanation: "i=1: 1×1=1, 1×2=2. i=2: 2×1=2, 2×2=4. i=3: 3×1=3, 3×2=6. Output: \"1 2 2 4 3 6 \"." },
  { id: "cf16", topic: "Control Flow", question: "How many times does the inner print execute?<pre><code>for (int i = 0; i < 4; i++)\n  for (int j = 0; j <= i; j++)\n    System.out.print(\"*\");</code></pre>", choices: ["4", "6", "8", "10", "16"], answer: 3, hint: "i=0: 1 time, i=1: 2 times, i=2: 3 times, i=3: 4 times", explanation: "1 + 2 + 3 + 4 = 10 total print calls." },

  // ── ACCUMULATION PATTERNS ──
  { id: "cf17", topic: "Control Flow", question: "What is the output?<pre><code>int sum = 0;\nfor (int i = 1; i <= 5; i++)\n  sum += i;\nSystem.out.println(sum);</code></pre>", choices: ["5", "10", "15", "20", "25"], answer: 2, hint: "Sum of 1+2+3+4+5", explanation: "sum = 1+2+3+4+5 = 15." },
  { id: "cf18", topic: "Control Flow", question: "What is the output?<pre><code>int prod = 1;\nfor (int i = 1; i <= 4; i++)\n  prod *= i;\nSystem.out.println(prod);</code></pre>", choices: ["4", "10", "16", "24", "256"], answer: 3, hint: "This computes 4! (factorial of 4)", explanation: "prod = 1×1×2×3×4 = 24 (4! = 24)." },
  { id: "cf19", topic: "Control Flow", question: "What is the output?<pre><code>int count = 0;\nfor (int i = 1; i <= 20; i++)\n  if (i % 3 == 0) count++;\nSystem.out.println(count);</code></pre>", choices: ["3", "5", "6", "7", "10"], answer: 2, hint: "Count multiples of 3 from 1 to 20: 3,6,9,12,15,18", explanation: "Multiples of 3 up to 20: 3, 6, 9, 12, 15, 18. Count = 6." },
  { id: "cf20", topic: "Control Flow", question: "What is the output?<pre><code>String s = \"hello\";\nint vowels = 0;\nfor (int i = 0; i < s.length(); i++) {\n  char c = s.charAt(i);\n  if (c=='a'||c=='e'||c=='i'||c=='o'||c=='u')\n    vowels++;\n}\nSystem.out.println(vowels);</code></pre>", choices: ["1", "2", "3", "4", "5"], answer: 1, hint: "Count vowels in \"hello\": h-e-l-l-o", explanation: "\"hello\": e (vowel), o (vowel). vowels = 2." },

  // ── TRACING COMPLEX LOOPS ──
  { id: "cf21", topic: "Control Flow", question: "What is the output?<pre><code>int x = 0;\nfor (int i = 0; i < 3; i++)\n  for (int j = i; j < 3; j++)\n    x++;\nSystem.out.println(x);</code></pre>", choices: ["3", "4", "5", "6", "9"], answer: 3, hint: "i=0: j runs 0,1,2 (3 times). i=1: j runs 1,2 (2 times). i=2: j runs 2 (1 time)", explanation: "i=0: 3 iterations. i=1: 2 iterations. i=2: 1 iteration. Total: 3+2+1 = 6." },
  { id: "cf22", topic: "Control Flow", question: "What is the output?<pre><code>int result = 0;\nfor (int i = 1; i <= 3; i++)\n  for (int j = 1; j <= 3; j++)\n    if (i != j) result += i + j;\nSystem.out.println(result);</code></pre>", choices: ["12", "18", "24", "30", "36"], answer: 2, hint: "For each pair (i,j) where i≠j, add i+j to result", explanation: "Pairs where i≠j: (1,2)=3, (1,3)=4, (2,1)=3, (2,3)=5, (3,1)=4, (3,2)=5. Sum = 3+4+3+5+4+5 = 24." },
  { id: "cf23", topic: "Control Flow", question: "What is the output?<pre><code>int n = 12345;\nint sum = 0;\nwhile (n > 0) {\n  sum += n % 10;\n  n /= 10;\n}\nSystem.out.println(sum);</code></pre>", choices: ["5", "10", "12", "15", "20"], answer: 3, hint: "This extracts and sums each digit: 5+4+3+2+1", explanation: "Digit sum: 5+4+3+2+1 = 15." },
  { id: "cf24", topic: "Control Flow", question: "What is the output?<pre><code>int n = 7, fib1 = 0, fib2 = 1;\nfor (int i = 2; i <= n; i++) {\n  int temp = fib1 + fib2;\n  fib1 = fib2;\n  fib2 = temp;\n}\nSystem.out.println(fib2);</code></pre>", choices: ["8", "11", "13", "15", "21"], answer: 2, hint: "This computes the nth Fibonacci number. F(7) = 13", explanation: "Fibonacci: 0,1,1,2,3,5,8,13. F(7) = 13." },
];
