// UIL Computer Science – Java Basics (Expressions, Output, Data Types, Operators)
const JAVA_BASICS_PROBLEMS = [

  // ── ARITHMETIC EXPRESSIONS ──
  { id: "jb1", topic: "Java Basics", question: "What is the value of the expression <code>17 / 5 + 17 % 5</code> in Java?", choices: ["3", "5", "5.4", "6", "7"], answer: 1, hint: "Integer division truncates: 17/5 = 3, and 17%5 = 2", explanation: "17/5 = 3 (integer division). 17%5 = 2. 3 + 2 = 5." },
  { id: "jb2", topic: "Java Basics", question: "What does <code>System.out.println(2 + 3 + \"hello\" + 4 + 5);</code> print?", choices: ["\"23hello45\"", "\"5hello45\"", "\"5hello9\"", "\"14hello\"", "\"2345hello\""], answer: 1, hint: "Left to right: 2+3=5 (int), then concatenation starts with the String", explanation: "2+3=5 (int addition), then 5+\"hello\"=\"5hello\", then \"5hello\"+4=\"5hello4\", then +5=\"5hello45\"." },
  { id: "jb3", topic: "Java Basics", question: "What is the value of <code>(double)(7 / 2) + 0.5</code>?", choices: ["3.5", "4.0", "4.5", "3.0", "4.25"], answer: 0, hint: "Integer division happens first (7/2=3), then the cast to double", explanation: "7/2 = 3 (integer division). (double)3 = 3.0. 3.0 + 0.5 = 3.5." },
  { id: "jb4", topic: "Java Basics", question: "What is the value of <code>7.0 / 2</code> in Java?", choices: ["3", "3.0", "3.5", "4", "4.0"], answer: 2, hint: "When one operand is double, the result is double division", explanation: "7.0 / 2 performs double division = 3.5." },
  { id: "jb5", topic: "Java Basics", question: "What is the result of <code>-13 % 5</code> in Java?", choices: ["&minus;3", "&minus;2", "2", "3", "0"], answer: 0, hint: "In Java, the result of % has the same sign as the dividend", explanation: "In Java, −13 % 5 = −3 (the sign follows the dividend). −13 = (−2)×5 + (−3)." },

  // ── INCREMENT / DECREMENT ──
  { id: "jb6", topic: "Java Basics", question: "What is the output?<pre><code>int x = 5;\nSystem.out.println(x++ + ++x);</code></pre>", choices: ["10", "11", "12", "13", "14"], answer: 2, hint: "x++ uses 5 then increments; ++x increments first then uses 7", explanation: "x++ evaluates to 5 (x becomes 6). ++x makes x 7, evaluates to 7. 5 + 7 = 12." },
  { id: "jb7", topic: "Java Basics", question: "What is the output?<pre><code>int a = 10;\nint b = a-- - --a;\nSystem.out.println(b);</code></pre>", choices: ["0", "1", "2", "3", "4"], answer: 2, hint: "a-- uses 10 (a→9), then --a makes a 8 and uses 8", explanation: "a-- evaluates to 10 (a becomes 9). --a makes a=8, evaluates to 8. b = 10 − 8 = 2." },
  { id: "jb8", topic: "Java Basics", question: "What is the output?<pre><code>int n = 3;\nn += n++ * 2;\nSystem.out.println(n);</code></pre>", choices: ["9", "10", "11", "12", "15"], answer: 0, hint: "n += expr is n = n + expr. n++ uses 3 then increments", explanation: "n += n++ * 2 → n = 3 + (3 * 2) = 3 + 6 = 9 (n++ yields 3, then n increments but is overwritten)." },

  // ── PRINT / PRINTF ──
  { id: "jb9", topic: "Java Basics", question: "What is the output of <code>System.out.printf(\"%d %s %d\", 3, \"plus\", 4);</code>?", choices: ["\"3 plus 4\"", "\"%d %s %d\"", "\"3plus4\"", "Compilation error", "\"3 \\\"plus\\\" 4\""], answer: 0, hint: "%d formats integers, %s formats strings", explanation: "%d → 3, %s → \"plus\", %d → 4. Output: \"3 plus 4\"." },
  { id: "jb10", topic: "Java Basics", question: "What is the output of <code>System.out.printf(\"%.2f\", 3.14159);</code>?", choices: ["\"3.14\"", "\"3.15\"", "\"3.14159\"", "\"3.1\"", "\"03.14\""], answer: 0, hint: "%.2f rounds to 2 decimal places", explanation: "%.2f formats to 2 decimal places: 3.14 (truncated/rounded from 3.14159)." },
  { id: "jb11", topic: "Java Basics", question: "What does <code>System.out.println(\"Hello\\nWorld\");</code> print?", choices: ["Hello\\nWorld", "HelloWorld", "Hello<br>World (on two lines)", "Hello World", "Compilation error"], answer: 2, hint: "\\n is the newline escape sequence", explanation: "\\n is the newline character, so \"Hello\" prints on one line and \"World\" on the next." },
  { id: "jb12", topic: "Java Basics", question: "What is the output of <code>System.out.println(\"A\" + \"B\" + 3 + 4);</code>?", choices: ["\"AB34\"", "\"AB7\"", "\"AB 34\"", "\"A B 3 4\"", "Compilation error"], answer: 0, hint: "String concatenation proceeds left to right once a String is involved", explanation: "\"A\"+\"B\" = \"AB\", then \"AB\"+3 = \"AB3\", then \"AB3\"+4 = \"AB34\"." },

  // ── DATA TYPES & CASTING ──
  { id: "jb13", topic: "Java Basics", question: "What is the value of <code>(int) 9.7 + (int) 0.8</code>?", choices: ["9", "10", "11", "9.5", "10.5"], answer: 0, hint: "Casting double to int truncates (does not round)", explanation: "(int)9.7 = 9, (int)0.8 = 0. 9 + 0 = 9." },
  { id: "jb14", topic: "Java Basics", question: "Which of the following will cause a compilation error?", choices: ["<code>int x = 5.0;</code>", "<code>double x = 5;</code>", "<code>int x = (int)5.0;</code>", "<code>double x = 5.0f;</code>", "<code>long x = 5;</code>"], answer: 0, hint: "Narrowing conversions require an explicit cast in Java", explanation: "int x = 5.0 is a narrowing conversion from double to int, which requires an explicit cast. This causes a compilation error." },
  { id: "jb15", topic: "Java Basics", question: "What is the result of <code>(char)('A' + 3)</code>?", choices: ["'C'", "'D'", "'E'", "68", "65"], answer: 1, hint: "'A' has ASCII value 65. 65 + 3 = 68", explanation: "'A' = 65. 65 + 3 = 68. (char)68 = 'D'." },
  { id: "jb16", topic: "Java Basics", question: "In Java, what is the size of an <code>int</code> in bits?", choices: ["8", "16", "32", "64", "platform-dependent"], answer: 2, hint: "Java primitive sizes are fixed: byte=8, short=16, int=32, long=64", explanation: "An int is always 32 bits (4 bytes) in Java, regardless of platform." },
  { id: "jb17", topic: "Java Basics", question: "What is the maximum value of a Java <code>byte</code>?", choices: ["127", "128", "255", "256", "511"], answer: 0, hint: "byte is 8-bit signed: range is &minus;128 to 127", explanation: "A byte is 8-bit signed two's complement: range −128 to 127. Max value is 127." },
  { id: "jb18", topic: "Java Basics", question: "What happens when you assign <code>byte b = (byte) 130;</code>?", choices: ["b = 130", "b = &minus;126", "b = &minus;128", "Compilation error", "Runtime error"], answer: 1, hint: "130 overflows a byte. 130 &minus; 256 = &minus;126", explanation: "130 exceeds byte range (−128 to 127). It wraps around: 130 − 256 = −126." },

  // ── ORDER OF OPERATIONS ──
  { id: "jb19", topic: "Java Basics", question: "What is the value of <code>3 + 4 * 2 - 6 / 3</code>?", choices: ["5", "7", "9", "11", "3"], answer: 2, hint: "Multiplication and division bind tighter than + and &minus;", explanation: "4*2 = 8, 6/3 = 2. Then 3 + 8 − 2 = 9." },
  { id: "jb20", topic: "Java Basics", question: "What is the value of <code>15 % 4 * 3 + 2</code>?", choices: ["5", "9", "11", "14", "17"], answer: 2, hint: "% and * have equal precedence and associate left to right", explanation: "15%4 = 3. 3*3 = 9. 9+2 = 11." },
  { id: "jb21", topic: "Java Basics", question: "What is the value of <code>2 + 3 * 4 % 5 - 1</code>?", choices: ["1", "2", "3", "4", "5"], answer: 2, hint: "* and % are evaluated before + and &minus;, left to right", explanation: "3*4 = 12. 12%5 = 2. 2 + 2 − 1 = 3." },

  // ── ASSIGNMENT OPERATORS ──
  { id: "jb22", topic: "Java Basics", question: "What is the output?<pre><code>int x = 10;\nx -= 3;\nx *= 2;\nSystem.out.println(x);</code></pre>", choices: ["4", "7", "14", "17", "20"], answer: 2, hint: "x &minus;= 3 makes x = 7, then x *= 2 makes x = 14", explanation: "x = 10 − 3 = 7. Then x = 7 * 2 = 14." },
  { id: "jb23", topic: "Java Basics", question: "What is the output?<pre><code>int a = 20;\na /= 3;\na %= 4;\nSystem.out.println(a);</code></pre>", choices: ["0", "1", "2", "3", "6"], answer: 2, hint: "20/3 = 6 (integer division), then 6%4 = 2", explanation: "a = 20/3 = 6 (integer division). a = 6%4 = 2." },

  // ── ESCAPE SEQUENCES ──
  { id: "jb24", topic: "Java Basics", question: "What does <code>System.out.println(\"She said \\\"Hi\\\"\");</code> output?", choices: ["She said \\\"Hi\\\"", "She said \"Hi\"", "She said Hi", "Compilation error", "She said ''Hi''"], answer: 1, hint: "\\\" is the escape sequence for a literal double quote", explanation: "\\\" prints a literal double-quote character. Output: She said \"Hi\"." },
  { id: "jb25", topic: "Java Basics", question: "How many characters does the String <code>\"A\\tB\\n\"</code> contain?", choices: ["3", "4", "5", "6", "7"], answer: 1, hint: "\\t is one character (tab), \\n is one character (newline)", explanation: "'A' + '\\t' + 'B' + '\\n' = 4 characters." },
];
