// UIL Computer Science – String Class & Math Class Methods
const STRINGS_MATH_PROBLEMS = [

  // ── STRING METHODS ──
  { id: "sm1", topic: "Strings & Math", question: "What is the output of <code>\"Computer\".substring(3, 6)</code>?", choices: ["\"put\"", "\"mpu\"", "\"pute\"", "\"mput\"", "\"uter\""], answer: 0, hint: "substring(start, end) extracts from index start to end&minus;1", explanation: "\"Computer\": indices C(0) o(1) m(2) p(3) u(4) t(5) e(6) r(7). substring(3,6) = \"put\"." },
  { id: "sm2", topic: "Strings & Math", question: "What does <code>\"Hello World\".indexOf(\"lo\")</code> return?", choices: ["2", "3", "4", "5", "&minus;1"], answer: 1, hint: "indexOf returns the starting index of the first occurrence", explanation: "\"lo\" starts at index 3 in \"Hello World\"." },
  { id: "sm3", topic: "Strings & Math", question: "What is the value of <code>\"Java\".charAt(2)</code>?", choices: ["'J'", "'a'", "'v'", "'A'", "IndexOutOfBoundsException"], answer: 2, hint: "charAt(index) uses 0-based indexing: J(0) a(1) v(2) a(3)", explanation: "Index 0='J', 1='a', 2='v', 3='a'. charAt(2) = 'v'." },
  { id: "sm4", topic: "Strings & Math", question: "What is the output of <code>\"racecar\".length()</code>?", choices: ["5", "6", "7", "8", "9"], answer: 2, hint: "Count each character: r-a-c-e-c-a-r", explanation: "\"racecar\" has 7 characters." },
  { id: "sm5", topic: "Strings & Math", question: "What does <code>\"Hello\".toUpperCase().substring(1, 3)</code> return?", choices: ["\"EL\"", "\"HE\"", "\"ELL\"", "\"el\"", "\"LL\""], answer: 0, hint: "First convert to \"HELLO\", then take substring(1,3)", explanation: "\"Hello\".toUpperCase() = \"HELLO\". substring(1,3) = \"EL\"." },
  { id: "sm6", topic: "Strings & Math", question: "What is the output of <code>\"abcabc\".lastIndexOf(\"bc\")</code>?", choices: ["1", "2", "4", "5", "3"], answer: 2, hint: "lastIndexOf finds the last occurrence of the substring", explanation: "\"bc\" appears at index 1 and index 4. lastIndexOf returns 4." },
  { id: "sm7", topic: "Strings & Math", question: "What does <code>\"Hello\".compareTo(\"Help\")</code> return?", choices: ["A negative number", "0", "A positive number", "true", "Compilation error"], answer: 0, hint: "Compares char by char: 'l' vs 'p'. 'l' < 'p'", explanation: "\"Hello\" vs \"Help\": first difference is index 3 ('l' vs 'p'). 'l'(108) − 'p'(112) = −4, a negative number." },
  { id: "sm8", topic: "Strings & Math", question: "What is the result of <code>\"Java\".equals(\"java\")</code>?", choices: ["true", "false", "0", "Compilation error", "Runtime error"], answer: 1, hint: "equals() is case-sensitive", explanation: "equals() is case-sensitive. \"Java\" ≠ \"java\". Returns false." },
  { id: "sm9", topic: "Strings & Math", question: "What does <code>\"Mississippi\".replace('s', 'z')</code> return?", choices: ["\"Mizzizzippi\"", "\"Mizzissippi\"", "\"Mississzppi\"", "\"Mizzizzppi\"", "\"Mizzizsippi\""], answer: 0, hint: "replace(old, new) replaces ALL occurrences", explanation: "All 's' characters become 'z': \"Mizzizzippi\"." },
  { id: "sm10", topic: "Strings & Math", question: "What is the output?<pre><code>String s = \"12345\";\nSystem.out.println(s.substring(2) + s.substring(0, 2));</code></pre>", choices: ["\"34512\"", "\"12345\"", "\"45123\"", "\"23451\"", "\"34521\""], answer: 0, hint: "substring(2) gives chars from index 2 onward; substring(0,2) gives first 2 chars", explanation: "s.substring(2) = \"345\". s.substring(0,2) = \"12\". Concatenated: \"34512\"." },

  // ── STRING PARSING ──
  { id: "sm11", topic: "Strings & Math", question: "What is the value of <code>Integer.parseInt(\"1010\", 2)</code>?", choices: ["5", "8", "10", "1010", "42"], answer: 2, hint: "The second parameter specifies the radix (base 2)", explanation: "Parses \"1010\" as binary: 1×8 + 0×4 + 1×2 + 0×1 = 10." },
  { id: "sm12", topic: "Strings & Math", question: "What does <code>\"10 20 30\".split(\" \").length</code> return?", choices: ["1", "2", "3", "6", "10"], answer: 2, hint: "split(\" \") splits on spaces, creating an array of substrings", explanation: "Splitting \"10 20 30\" by spaces produces [\"10\", \"20\", \"30\"], which has length 3." },
  { id: "sm13", topic: "Strings & Math", question: "What does <code>Double.parseDouble(\"3.14\")</code> return?", choices: ["3", "3.0", "3.14", "\"3.14\"", "Compilation error"], answer: 2, hint: "parseDouble converts the string representation to a double", explanation: "Double.parseDouble(\"3.14\") returns the double value 3.14." },

  // ── MATH CLASS ──
  { id: "sm14", topic: "Strings & Math", question: "What is the value of <code>Math.abs(-7) + Math.abs(3)</code>?", choices: ["4", "7", "10", "&minus;4", "&minus;10"], answer: 2, hint: "Math.abs() returns the absolute (positive) value", explanation: "Math.abs(−7) = 7. Math.abs(3) = 3. 7 + 3 = 10." },
  { id: "sm15", topic: "Strings & Math", question: "What does <code>Math.pow(2, 10)</code> return?", choices: ["20.0", "100.0", "512.0", "1024.0", "2048.0"], answer: 3, hint: "Math.pow(base, exponent) computes base<sup>exponent</sup>", explanation: "Math.pow(2, 10) = 2¹⁰ = 1024.0." },
  { id: "sm16", topic: "Strings & Math", question: "What does <code>Math.sqrt(144)</code> return?", choices: ["11.0", "12.0", "13.0", "72.0", "144.0"], answer: 1, hint: "Math.sqrt() returns the square root", explanation: "Math.sqrt(144) = 12.0." },
  { id: "sm17", topic: "Strings & Math", question: "What does <code>Math.max(Math.min(5, 8), Math.min(3, 7))</code> return?", choices: ["3", "5", "7", "8", "15"], answer: 1, hint: "Evaluate inner calls first: min(5,8)=5, min(3,7)=3, then max(5,3)", explanation: "Math.min(5,8) = 5. Math.min(3,7) = 3. Math.max(5,3) = 5." },
  { id: "sm18", topic: "Strings & Math", question: "What does <code>Math.floor(3.9)</code> return?", choices: ["3", "3.0", "4", "4.0", "3.9"], answer: 1, hint: "Math.floor returns the largest double ≤ the argument", explanation: "Math.floor(3.9) = 3.0 (returns a double, not int)." },
  { id: "sm19", topic: "Strings & Math", question: "What does <code>Math.ceil(-2.3)</code> return?", choices: ["&minus;3.0", "&minus;2.0", "&minus;2.3", "2.0", "3.0"], answer: 1, hint: "Math.ceil returns the smallest double ≥ the argument", explanation: "Math.ceil(−2.3) = −2.0 (rounds toward positive infinity)." },
  { id: "sm20", topic: "Strings & Math", question: "What does <code>(int)(Math.random() * 6) + 1</code> produce?", choices: ["A random int from 0 to 5", "A random int from 1 to 6", "A random int from 0 to 6", "A random int from 1 to 7", "A random double from 1.0 to 6.0"], answer: 1, hint: "Math.random() returns [0.0, 1.0), multiply by 6 gives [0.0, 6.0), cast to int gives 0-5, add 1 gives 1-6", explanation: "Math.random() ∈ [0,1). ×6 → [0,6). (int) → 0..5. +1 → 1..6." },

  // ── CHARACTER CLASS ──
  { id: "sm21", topic: "Strings & Math", question: "What does <code>Character.isDigit('7')</code> return?", choices: ["true", "false", "7", "'7'", "Compilation error"], answer: 0, hint: "isDigit checks if the character is a numeric digit 0-9", explanation: "'7' is a digit character, so Character.isDigit('7') returns true." },
  { id: "sm22", topic: "Strings & Math", question: "What is the value of <code>'Z' - 'A'</code> in Java?", choices: ["24", "25", "26", "0", "Compilation error"], answer: 1, hint: "Characters are subtracted by their ASCII/Unicode values: 'Z'=90, 'A'=65", explanation: "'Z'(90) − 'A'(65) = 25." },
  { id: "sm23", topic: "Strings & Math", question: "What is the output of <code>System.out.println('A' + 1);</code>?", choices: ["'B'", "\"A1\"", "66", "B", "Compilation error"], answer: 2, hint: "char + int produces an int in Java", explanation: "'A' (65) + 1 = 66. Since char + int yields int, it prints 66." },
];
